# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin enable properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.vci-plugin=MockCSVDataProviderPlugin
mosip.certify.plugin-mode=DataProvider

# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration=P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1

mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/

# CSV specific properties
mosip.certify.mock.data-provider.csv.identifier-column=id
mosip.certify.mock.data-provider.csv.data-columns=id,givenName,familyName,birthDate,documentNumber,portrait,drivingPrivileges
mosip.certify.mock.data-provider.csv-registry-uri=https://raw.githubusercontent.com/inji/inji-config/refs/heads/released/driving_license_data.csv

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.mdl.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mock.identity.esignet.host}
mosip.certify.database.name=inji_certify_mdl
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.mdl.security.pin:${softhsm.certify.security.pin}}
# Add Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Mock Mobile Driving License',\
    'locale': 'en'\
  }\
}
# Override proof types supported for the credential config
mosip.certify.credential-config.proof-types-supported={\
  'jwt': {'proof_signing_alg_values_supported': {'ES256'}}\
}

# Set the key prefix for Redis cache
mosip.certify.cache.redis.key-prefix=${mosip.injicertify.mdl.host}::